### ISSUE TITLE
Actual size of the dataset & images

### ISSUE THREAD

**Issue by pabloppp** [google-research-datasets/wit#1]
First of all, thanks for this awesome dataset, I believe it will be used for many interesting applications. 🎉 

It seems that the files you provide only contain the image URLs, the 25Gb is only for the text & URLs, so I was wondering what is the actual size of the dataset once all images have been downloaded.

Also, I started downloading some images for a quick test, I only picked a subset of the 1% data sample, consisting of the images that have a non-empty `caption_reference_description` in English (about 32K rows, although some of the URLs are broken) and it's already taking a pretty long time to download, so I imagine that downloading the full dataset could take days, so are you planning on sharing one (or many) downloadable compressed packs for the images? 

Thank you again!

**Comment by krishna2** [comment]
Thanks much for the compliments and for trying out our dataset. Yes, the 25GB is only counting the text and the urls provided for download. There are 11M+ unique images in the dataset - so it will be a few TB.

As of now, we aren't providing images (due to licensing and other restrictions). But we are discussing some ideas around this topic. Plus we are planning a competition with our held out set. Please kindly stay tuned for any updates.

**Comment by dinhanhx** [comment]
> There are 11M+ unique images in the dataset - so it will be a few TB.

@krishna2 @pabloppp this is a correct approximation. I have just crawled around 150K images which is already 200 GBs (for the original resolution). 

https://huggingface.co/datasets/dinhanhx/google-wit-vi
